### ISSUE TITLE
关于乖巧模式设置里的保护有通知的应用

### ISSUE THREAD

**Issue by DoveKi** [Tornaco/Xposed-Application-Management-Mod#259]
有办法只单独保护某应用么？

**Comment by Tornaco** [comment]
@DoveKi 后面最快的开发方式就是加规则支持。如果需要可以进行开发。

**Comment by DoveKi** [comment]
希望能加上规则支持 只有音乐播放器 加速器 下载器之类的应用运行的时候必须保护很有用 像微信之类的消息通知根本不需要保护
