### ISSUE TITLE
强烈建议加入网络控制

### ISSUE THREAD

**Issue by Seele0oO** [Tornaco/Xposed-Application-Management-Mod#424]
网络控制大概是这个程序中缺少的非常重要的东西了，系统的手机管家压不住某些软件的联网。只能找找更好权限的管理器。

**Comment by RayZhan** [comment]
联网控制可以试下afwall，我觉得还蛮好用的

**Comment by aorosora** [comment]
有啊，aio版本啊

**Comment by ding667** [comment]
> 有啊，aio版本啊

？？？哪里

**Comment by 2220209876** [comment]
> 联网控制可以试下afwall，我觉得还蛮好用的

afw有些APP显示不出来

**Comment by RayZhan** [comment]
> > 联网控制可以试下afwall，我觉得还蛮好用的
> 
> afw有些APP显示不出来

没有联网权限的不会显示，当然也不排除有的软件自己弄个iptable来联网
